name: Build A133
on: push
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: sudo apt install -y gcc-arm-none-eabi device-tree-compiler python3-setuptools swig
      - run: make liontron-h-a133l_defconfig
      - run: make CROSS_COMPILE=arm-none-eabi- -j$(nproc)
      - uses: actions/upload-artifact@v4
        with:
          name: u-boot-a133
          path: u-boot-sunxi-with-spl.bin
